
//*********************************
//Oracle class for Bulls and Cows
//
//
//*********************************

public class Oracle {
                
        private String target; // target is the number the oracle generates. Treated as a string

        public Oracle() {
                
                target = generateTarget(); // initializing it to the number generated by the oracle
        }

        private String generateTarget() {
                String str = ""; //digits will be added to this blank string
                String newDigit;
  
                for (int i=0; i<4; i++) { //loop until we get four digits
                    	newDigit = ""+(int)(Math.random()*9.999);// digit generated from 0 to 9 randomly. Using 9.999 so that distribution is equal.
                        while (str.contains(newDigit)) { // oracle generates another digit if the original digit is already in str
                                newDigit = ""+(int)(Math.random()*9.999);
                        }
                        str=str.concat(newDigit);
                }
               
                return str; 
        }
         
        public String getTarget() {
                return target;
        }

        public void displayBulls(String input) { //shows bulls based on parameter: user input
                int bulls = calculateBulls(input);
                System.out.println("Number of bulls: " + bulls);
        }

        public int calculateBulls(String input) { //method for calculating bulls based on user input
                int totalBulls = 0;
                int i=0;
                while(i<4) {//loop for all four digits
                        if (input.charAt(i)==target.charAt(i))//compares characters of the guess and the number
                                totalBulls=totalBulls+1; //increment if there is a match
                                i++;
                }
                return totalBulls;
        }
                         
        public void displayCows(String input) {
                int cows = calculateCows(input);
                System.out.println("Number of cows: " + cows);
        }

        public int calculateCows(String input) {
                int totalCows = 0;
                for (int j=0; j<4; j++) { //pertains to the digits of the guess
                        for (int i=0; i<4; i++){// digits of the number
                                if (target.charAt(i)==input.charAt(j) && target.charAt(i) != input.charAt(i)){ //checking if digit is right but in wrong place
                                	boolean duplicateAfterwards=false; // accounting for repeated digit
                                	for (int k=j+1; k<4; k++)
                                		if (input.charAt(j)==input.charAt(k)&&k!=i)
                                			duplicateAfterwards=true;
                                	if (!duplicateAfterwards) // only the last repeated digit will be accounted for a cow
                                		totalCows++;
                                    break; // no need to continue iterations once a cow has been found. We can move onto the outer loop.
                                }
                        }
                }
                return totalCows;
        }
}
                
